[package]
name = "http-rust"
version = "0.1.0"
authors = ["Mayank17M <mamgain.mayank01@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
